### ISSUE TITLE
Sidebar Stops Scrolling

### ISSUE THREAD

**Issue by MisterMoody** [MisterMoody/mistermoody.github.io#1]
I have an 'active' link set on a sidebar scroll that once the content gets to a certain point the scroll stops scrolling. Not sure what the issue is. Need to come back to this because I think its an easy fix, but offering it to the webiverse as a 'good first issue.'

``nav {
 white-space: nowrap;
  background: #333;
}``

``nav ul {
  list-style: none;
  margin: 0;
  padding: 2em 0;
}``

``@media (min-height: 300px) {
  nav ul {
    position: sticky;
    top: 8px;
  }
}``

``nav ul li a {
  display: block;
  padding: 0.5rem 0rem;
  color: white;
  text-decoration: none;
}``

``.nested {
  display: none;
  margin: -8px 0;
  padding: 0rem 2rem;
  font-size: 0.88rem;
}``

``nav ul li a.current {
  color: red;
}``

**Comment by ChonPaSa** [comment]
I can't reproduce the issue. Please provide the steps to reproduce

**Comment by MisterMoody** [comment]
Open the ``main.css`` file and remove Line 122 of the ``.nested`` class "``display: none;``"
Next, scroll to the 'Using Unicode' sub-topic section; from that point I want the ``<li>`` to 'scroll UP' with the page so that the list-item is visible on the sidebar as the user continues to browse content.
![gitissue1](https://user-images.githubusercontent.com/10537291/50543676-a4e0ff00-0bac-11e9-9c57-6dc8b3dbe467.JPG)

**Comment by ChonPaSa** [comment]
When one of the sections is missing there is an TypeError: section is null and the scrolling stops.
The secMain was missing and conAdvanced was commented. I added the first one for testing and uncommented the second one and it seems to work. I will send you a pull request

**Comment by ChonPaSa** [comment]
ah, yeah. No rights

**Comment by MisterMoody** [comment]
Not sure why you were denied rights as I have not set any restrictions on the repo. 
I hope you forked the repo then requested a pull request, but if you performed another action let me know.

Will evaluate code shortly then see what we can do to about the pull request!

Thank you for your continued support!

Resources:
https://help.github.com/articles/about-pull-requests/
https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Comment by ChonPaSa** [comment]
I was trying with Github desktop. Now, directly in the website it worked ;)

**Comment by MisterMoody** [comment]
Awesome! Will review soon.

**Comment by MisterMoody** [comment]
Thank you for your assistance!
